services:
  python-app:
    build:
      context: .
    container_name: exit-game-backend
    restart: unless-stopped
    init: true
    ports:
      - "8000:8000"  # Exposes FastAPI default port
    # env_file: ./.env  # Uncomment if .env file exists
    # Add depends_on here if you add external services
    # networks: [default]  # Uncomment if you add more services/networks

# No external services (databases, caches, etc.) detected in the project files or documentation.
# No volumes section included, as there are no persistent data requirements.
